version: "3"

services:
  php:
    # PROD
    # image: demophp:latest
    # volumes:
    #   - ./.env:/var/www/html/.env

    # DEV
    build:
      context: .
    volumes:
      - ./:/var/www/html

  web:
    ports:
      - "80:80"

    # PROD
    # image: demonginx:latest

    # DEV
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:5
    volumes:
      - airportredisdata:/data

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - airportmysqldata:/var/lib/mysql

volumes:
  airportmysqldata:
  airportredisdata:
